mamespace: prod

app:
  name: second-service
  label: second-service
  replicas: 4
  image:
    repository: hyeok1234565/k8s-second-service
    tag: 1.0.0
    pullPolicy: IfNotPresent
  port: 8082
  customCommand: []
  customArgs: []
  env: []
  resources: {}

service:
  type: ClusterIP
  port: 8082