apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-service
spec:
  destination:
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/KJH0476/cicd-k8s-manifest.git'
    targetRevision: main
    path: charts/first-service
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}