namespace: prod

app:
  name: first-service
  label: first-service
  replicas: 4
  image:
    repository: hyeok1234565/k8s-first-service
    tag: new-test
    pullPolicy: IfNotPresent
  port: 8081
  customCommand: []
  customArgs: []
  env: []
  resources: {}

service:
  type: ClusterIP
  port: 8081