apiVersion: v1
kind: Service
metadata:
  name: {{ include "first-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.label }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.app.label }}
