namespace: prod

app:
  name: third-service
  label: third-service
  replicas: 4
  image:
    repository: hyeok1234565/k8s-third-service
    tag: 1.0.0
    pullPolicy: IfNotPresent
  port: 8083
  customCommand: []
  customArgs: []
  env: []
  resources: {}

service:
  type: ClusterIP
  port: 8083